# Server configuration
server:
  address: ":8080" # Address and port to listen on

# Database configuration
database:
  host: "localhost" # Database host
  port: 5432        # Database port
  user: "user"      # Database username
  password: "password" # Database password
  dbname: "edidb"   # Database name

# Redis configuration (for caching)
redis:
  address: "localhost:6379" # Redis server address
  password: ""              # Redis password (if any)
  db: 0                     # Redis database number

# JWT configuration (for token generation and validation)
jwt:
  secret_key: "your-secret-key" # Secret key for signing JWT tokens
  expiration: 3600              # Token expiration time in seconds (1 hour)

# Logging configuration
logging:
  level: "info" # Log level (debug, info, warn, error, fatal)
  format: "json" # Log format (json, text)

# Prometheus configuration (for monitoring)
prometheus:
  enabled: true # Enable Prometheus metrics
  path: "/metrics" # Path for Prometheus metrics endpoint
